GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "Kyle"
}

###

GET http://localhost:5000/api/auth/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcxMjkxMTcwNn0.nt0KK4aBoL51POyPiaW22kIc_YEIrt7gzfIU4FXZJ8w