GET http://localhost:5000/api/users

###

DELETE http://localhost:5000/api/users/661be5303a3394fa82b8358a

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "Felix",
  "age": 45,
  "role": "Admin"
}

###

POST http://localhost:5000/api/sampleauth/login
Content-Type: application/json

{
  "username": "Kyle"
}

###

GET http://localhost:5000/api/example/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcxMjkxNjc5Mn0.QMdPqSIMaJ405iy02CXtO-HJYkVdQ6QlgiNURkbcrCQ
###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Maxima",
  "email": "maximi@gmail.com",
  "password": 123456,
  "isAdmin": false
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "maxi@gmail.com",
  "password": "123456"
}


// bcryptjs express-async-handler jsonwebtoken